apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "block-explorer.fullname" . }}
  labels:
    {{- include "block-explorer.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .secretName }}
  rules:
  - host: {{ .host | quote }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "block-explorer.fullname" . }}
            port:
              name: http
