name: build

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.lefthook/**'
      - '.vscode/**'
      - 'docs/**'
      - '**.md'
    branches:
      - main
      - cicd-work
  push:
    tags:
      - "v*"
    paths-ignore:
      - '.lefthook/**'
      - '.vscode/**'
      - 'docs/**'
      - '**.md'
    branches:
      - main
      - cicd-work

jobs:
  build:
    runs-on: [self-hosted, Linux, large]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Extract version
        uses: mobilecoinofficial/gha-k8s-toolbox@v1
        id: version_output
        with:
          action: generate-metadata
    
      - name: Setup Docker Buildx
        id: buildx
        if: "! contains(github.event.head_commit.message, '[skip docker]')"
        uses: docker/setup-buildx-action@v2
        with:
          install: true    