name: build

env:
  DOCKERHUB_ORG: mobilecoin
  REPO_NAME: block-explorer
  TARGET_CLUSTER: utility-r1-d-k8s
  CHART_REPO: https://harbor.mobilecoin.com/chartrepo/mobilecoinofficial-private
  CHART_PATH: ./.internal-ci/charts/block-explorer
  REACT_APP_RESERVE_AUDITOR_URL: https://auditor.mobilecoin.foundation/api
  REACT_APP_FULL_SERVICE_URL: https://readonly-fs-mainnet.mobilecoin.com/wallet/v2



on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.lefthook/**'
      - '.vscode/**'
      - 'docs/**'
      - '**.md'
    branches:
      - main
  push:
    tags:
      - "v*"
    paths-ignore:
      - '.lefthook/**'
      - '.vscode/**'
      - 'docs/**'
      - '**.md'
    branches:
      - main
      - cicd-work

jobs:
  build:
    runs-on: [self-hosted, Linux, large] # remove large instance after dev work

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Generate Docker Tags
        id: docker_meta
        users: docker/metadata-action@v4
        with:
          action: generate-metadata

      - name: Setup Docker Buildx
        id: buildx
        if: "! contains(github.event.head_commit.message, '[skip docker]')"
        uses: docker/setup-buildx-action@v2
        with:
          install: true    

      - name: Login to DockerHub
        if: "! contains(github.event.head_commit.message, '[skip docker]')"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish to DockerHub
        uses: docker/build-push-action@v3
        if: "! contains(github.event.head_commit.message, '[skip docker]')"
        id: docker-push
        with:
          context: .
          file: Dockerfile
          labels: ${{ steps.docker_meta.outputs.labels }}
          tags: ${{ env.DOCKERHUB_ORG }}/${{ env.REPO_NAME }}:${{ steps.docker_meta.outputs.tags }}
          push: true
          # fix caching later
          # cache-from: type=registry,ref=${{ env.DOCKERHUB_ORG }}/${{ env.REPO_NAME }}:buildcache-${{ steps.version_output.outputs.version }}
          # cache-to: type=registry,ref=${{ env.DOCKERHUB_ORG }}/${{ env.REPO_NAME }}:buildcache-${{ steps.version_output.outputs.version }}

      - name: Package and publish chart
        uses: mobilecoinofficial/gha-k8s-toolbox@v1
        with:
          action: helm-publish
          chart_repo_username: ${{ secrets.HARBOR_USERNAME }}
          chart_repo_password: ${{ secrets.HARBOR_PASSWORD }}
          chart_repo: ${{ env.CHART_REPO }}
          chart_app_version: ${{ steps.docker_meta.outputs.version }}
          chart_version: ${{ github.ref_name }}
          chart_path: ${{ env.CHART_PATH }}

  deploy:
    name: Deploy
    runs-on: [self-hosted, Linux]
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        if: "! contains(github.event.head_commit.message, '[deploy]')"

      - name: Create namespace
        uses: mobilecoinofficial/gha-k8s-toolbox@v1
        if: "! contains(github.event.head_commit.message, '[deploy]')"
        with:
          action: namespace-create
          namespace: block-explorer
          rancher_cluster: ${{ env.TARGET_CLUSTER }}
          rancher_url: ${{ secrets.RANCHER_B_URL }}
          rancher_token: ${{ secrets.RANCHER_B_TOKEN }}    

      - name: Deploy release
        uses: mobilecoinofficial/gha-k8s-toolbox@v1
        if: "! contains(github.event.head_commit.message, '[deploy]')"
        with:
          action: helm-deploy
          rancher_cluster: ${{ env.TARGET_CLUSTER }}
          namespace: block-explorer
          release_name: ${{ env.REPO_NAME }}
          rancher_url: ${{ secrets.RANCHER_B_URL }}
          rancher_token: ${{ secrets.RANCHER_B_TOKEN }}
          chart_repo_username: ${{ secrets.HARBOR_USERNAME }}
          chart_repo_password: ${{ secrets.HARBOR_PASSWORD }}
          chart_repo: ${{ env.CHART_REPO }}
          chart_name: ${{ env.REPO_NAME}}
          chart_version: ${{ github.ref_name }}
          chart_path: ${{ env.CHART_PATH }}

