name: build

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.lefthook/**'
      - '.vscode/**'
      - 'docs/**'
      - '**.md'
    branches:
      - main
      - cicd-work
  push:
    tags:
      - "v*"
    paths-ignore:
      - '.lefthook/**'
      - '.vscode/**'
      - 'docs/**'
      - '**.md'
    branches:
      - main
      - cicd-work

jobs:
  build:
    runs-on: [self-hosted, Linux, large]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
