name: deploy-prod

env:
  DOCKERHUB_ORG: mobilecoin
  REPO_NAME: block-explorer
  TARGET_CLUSTER: utility-r1-d-k8s
  CHART_REPO: https://harbor.mobilecoin.com/chartrepo/mobilecoinofficial-private
  CHART_PATH: ./.internal-ci/charts/block-explorer



on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: [self-hosted, Linux]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create namespace
        uses: mobilecoinofficial/gha-k8s-toolbox@v1
        with:
          action: namespace-create
          namespace: block-explorer
          rancher_cluster: ${{ env.TARGET_CLUSTER }}
          rancher_url: ${{ secrets.RANCHER_B_URL }}
          rancher_token: ${{ secrets.RANCHER_B_TOKEN }}    

      - name: Deploy release
        uses: mobilecoinofficial/gha-k8s-toolbox@v1
        with:
          action: helm-deploy
          rancher_cluster: ${{ env.TARGET_CLUSTER }}
          namespace: block-explorer
          release_name: ${{ env.REPO_NAME }}
          rancher_url: ${{ secrets.RANCHER_B_URL }}
          rancher_token: ${{ secrets.RANCHER_B_TOKEN }}
          chart_repo_username: ${{ secrets.HARBOR_USERNAME }}
          chart_repo_password: ${{ secrets.HARBOR_PASSWORD }}
          chart_repo: ${{ env.CHART_REPO }}
          chart_name: ${{ env.REPO_NAME}}
          chart_version: ${{ github.ref_name }}
          chart_path: ${{ env.CHART_PATH }}

